print("Ingrese 1 número: ")
input_numero = input()
numero = int(input_numero)
print("Ingrese otro número: ")
input_numero_2 = input()
numero_2 = int(input_numero_2)
print("Ingrese un último número: ")
input_numero_3 = input()
numero_3 = int(input_numero_3)
print("La Respuesta es: ", (numero + numero_2) * numero_3)